### ISSUE TITLE
Validate tight & full serializations against JavaScript implementation

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankj#4]
We need to ensure that this is a compatible implementation with the existing JavaScript version that is deployed at https://genobank.io/test/certificates/create-certificate.html?permitteeId=4

Some more details about how this works are shared at https://genobank.io/test/certificates/dev-playgroud.html Note there may be small differences between that file and our implementation in JavaScript above.

# Blockers

- [ ] https://github.com/Genobank/genobank.io/issues/211
- [ ] https://github.com/Genobank/genobank.io/issues/209

# Work plan

- [X] Develop a test set of parameters
  - Patient name = XXXX
  - Patient passport = YYYY
  - Procedure = 1 (COVID-19-PCR)
  - Result = N (NEGATIVE)
  - Serial = "" (empty string)
  - Time = 1611517330 (2021-01-24T19:42:10Z)
- [ ] Create a certificate on test network using the test account at https://github.com/Genobank/genobank.io/wiki/Test-Accounts-and-Certificates#permittee
  - [ ] Post the URL here and extract the serializations
  - [ ] (Alternatively, if you don't have access to the test account, you could study the JavaScript there and attached debugging to extract the serialized data.)
- [ ] Run the same test on genobankj
  - [ ] Post the serializations
- [ ] Fix genobankj so that the serializations match

**Comment by fulldecent** [comment]
Here is the complete output of the Java program working with these inputs:

```sh
java -jar target/certificates-1.0-SNAPSHOT-jar-with-dependencies.jar \
--test \
'wrong outside clever wagon father insane boy junk punch duck drift cupboard' 37 \
'NAME' \
'PASS123' \
'1' \
'N' \
'' \
1611517330
```

I assert that my program is working correctly and your JavaScript implementation and API is wrong as per this program output:

```
Blockchain Lab Results Certification
Java Certification Example, version 1.0
(c) GenoBank.io 🧬

USING TEST NETWORK ⭐

Loading account from TWELVE_WORD_PHRASE
Address:     0x13e541de78dacc48722ad4f4e9903e501b233706

Preparing representations
Tight:       NAME|PASS123|1|N||1611517330
Full:        io.genobank.test.certificates.v1.permittee-certification|NAME|PASS123|COVID-19-PCR|NEGATIVE||2021-01-24T19:42:10Z
Claim:       [B@612fc6eb

Signing
Address:     0x627306090abab3a6e1400e9345bc60c78a8bef57
R:           0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a3
S:           0x7ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e95
V:           0x1c
Signature:   0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c

Posting to API server
Preparing request to API server
URL:         https://api-test.genobank.io/certificates
Body:        {"claim":"0x48ff95192d8f7b6934fd079b4c5b9ade463e3aaefffc788c60a8ff58237b8c09","signature":"0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c","permitteeSerial":37}

Response:    {"errors":[{"code":400006,"message":""}],"id":"6032d864d8e6d80008de91f6","status":400}

Certificate URL
https://genobank.io/test/certificates/verify-certificate-v1#NAME%7CPASS123%7C1%7CN%7C%7C1611517330%7C0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c%7C9999999999%7C0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c
```

Please prove (as helpfully as possible) me wrong so I can update the Java implementation to match the JavaScript implementation.

**Comment by fulldecent** [comment]
^ help please @xpepermint @MoMannn

**Comment by MoMannn** [comment]
serialization itself has no effect on the API call, but does on verification part. From which I see there are some mistakes. (missing permitteeSerial, txHash etc.). You now have example for this in dev playground. I also made the code more modular so you have all serialization code in `certificate.js`.

**Comment by fulldecent** [comment]
I know reading code is fun but a repeatable test case is funner.

Please run using the exact inputs I have above and share your intermediary outputs. Does my program above match those?

**Comment by MoMannn** [comment]
Like I said you are missing permitteeSerial in the first serialization and txHash in the second.

**Comment by fulldecent** [comment]
Please run using the exact inputs I have above and share your output.

---

By using the words "you are missing permitteeSerial in the first serialization and txHash in the second" you are requiring me to make the changes and then check again with you if they are correct--costing another day because you (or I) are living on Neptune and the round-trip response time is 8 light-hours.

It will be much more helpful if you can say with certainty:

> You need to use XXX inputs and then YYY is the correct output.

because that is something I can directly validate against non-interactively.
