### ISSUE TITLE
Validate 12-word phrase is loading correct account

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankj#5]
The account that is loaded using genobankj from a mnemonic does not exactly match the one from the JavaScript implementation.

The JavaScript implementation is at https://genobank.io/test/certificates/create-certificate.html?permitteeId=4

# Work plan

- [ ] Create and sign a test certificate on the test network using the test account https://github.com/Genobank/genobank.io/wiki/Test-Accounts-and-Certificates#permittee
  - [ ] Be sure to use the 12-word phrase to create the certificate (NOT MetaMask)
  - [ ] Note below which account corresponds to that 12-word phrase
- [ ] Run genobankj using the same 12-word phrase
- [ ] Validate that genobankj is using the same account as the JavaScript implementation
- [ ] If they are not the same, update genobankj to match the JavaScript implementation

**Comment by fulldecent** [comment]
Here is the complete output of the Java program working with these inputs:

```sh
java -jar target/certificates-1.0-SNAPSHOT-jar-with-dependencies.jar \
--test \
'wrong outside clever wagon father insane boy junk punch duck drift cupboard' 37 \
'NAME' \
'PASS123' \
'1' \
'N' \
'' \
1611517330
```

I assert that my program is working correctly and your JavaScript implementation and API is wrong as per this program output:

```
Blockchain Lab Results Certification
Java Certification Example, version 1.0
(c) GenoBank.io 🧬

USING TEST NETWORK ⭐

Loading account from TWELVE_WORD_PHRASE
Address:     0x13e541de78dacc48722ad4f4e9903e501b233706

Preparing representations
Tight:       NAME|PASS123|1|N||1611517330
Full:        io.genobank.test.certificates.v1.permittee-certification|NAME|PASS123|COVID-19-PCR|NEGATIVE||2021-01-24T19:42:10Z
Claim:       [B@612fc6eb

Signing
Address:     0x627306090abab3a6e1400e9345bc60c78a8bef57
R:           0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a3
S:           0x7ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e95
V:           0x1c
Signature:   0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c

Posting to API server
Preparing request to API server
URL:         https://api-test.genobank.io/certificates
Body:        {"claim":"0x48ff95192d8f7b6934fd079b4c5b9ade463e3aaefffc788c60a8ff58237b8c09","signature":"0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c","permitteeSerial":37}

Response:    {"errors":[{"code":400006,"message":""}],"id":"6032d864d8e6d80008de91f6","status":400}

Certificate URL
https://genobank.io/test/certificates/verify-certificate-v1#NAME%7CPASS123%7C1%7CN%7C%7C1611517330%7C0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c%7C9999999999%7C0x97aa79692c2dc8f8628d9991f21b69d0980c58199e7e46ecaa6143be394cb4a37ad3d830855ce73545e8fdae1d47244c79430edc91bfe3d961f73ae2bc5c7e951c
```

Please prove (as helpfully as possible) me wrong so I can update the Java implementation to match the JavaScript implementation.

**Comment by fulldecent** [comment]
^ help please @xpepermint @MoMannn

**Comment by MoMannn** [comment]
In dev playground I load the same mnemonic and the address from mnemonic is the same: `0x13E541de78DaCC48722aD4F4E9903E501b233706`.

**Comment by MoMannn** [comment]
But permittee 37: https://api-test.genobank.io/permittees/37 does not belong to this address... Which server validates...

**Comment by fulldecent** [comment]
Thank you. That validates one thing. But then it illustrates another problem is broken.

# Blockers

- [ ] https://github.com/Genobank/genobank.io/issues/159

^^ please fix this so I have actual inputs that I can use for a test case

**Comment by MoMannn** [comment]
Fixed.
