### ISSUE TITLE
Update network implementation to touch our servers

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankj#7]
The real GenoBank.io platform uses a JSON REST API for certificates. This is documented at https://docs.genobank.io/api/#certificates

However genobankj only makes a request to httpbin.

# Work plan

- [ ] Update genobankj to connect to the correct test and production URLs
- [ ] Properly serialize outbound data (i.e. HTTP POST request)
- [ ] Demonstrate that the outbound data format matches the JavaScript implementation for an identical certificate (use a proxy server, Charles, Postman, etc to show this)
- [ ] Properly unserialize inbound data (i.e. HTTP response)
- [ ] Throw an error if inbound data is an unexpected format or represents an error
- [ ] If inbound data is successful status and in expected format then use that in the Platform.java / NotarizedCertificate
  - [ ] Fix `// TODO: use real time` based on HTTP response
  - [ ] Fix `// TODO: use from GenoBank respnose` based on HTTP response
