### ISSUE TITLE
Validate GenoBank.io server response

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankj#8]
In NotarizedCertificate.java, we hold all the data structures and have the server signature.

Currently we do not check the server response.

# Work plan

- [ ] Add a hard coded GenoBank.io account into the `Network` enumeration
- [ ] Update `validateNotarization` to use ECRECOVER to get the signing account
- [ ] Update `validateNotarization` to confirm the expected GenoBank.io account did sign the message, or throw error if the correct account was not found
